/**
 * @file ai-engine.ts
 * @responsibility Definition of data contracts and response structures for the AI Carbon Coach
 * including generated archetypes, climate twin projections, and customized signature missions.
 */

/**
 * Raw answers collected during the 6-question conversational onboarding with Clover.
 *
 * These values are sent directly to the `/api/profile` endpoint where they are
 * validated via Zod and forwarded to `calculateProfile` in `scoring-engine.ts`.
 *
 * @property city      - Free-text city name used for grid-intensity lookup.
 * @property transport - Transport mode enum key (e.g. `"walk_bike"`, `"gas_car"`).
 * @property food      - Diet type enum key (e.g. `"vegan"`, `"meat_heavy"`).
 * @property shopping  - Shopping frequency enum key (e.g. `"minimalist"`, `"frequent"`).
 * @property energy    - Home energy type enum key (e.g. `"solar"`, `"ac_heavy"`).
 * @property name      - Optional display name entered in the first chat question.
 */
export interface OnboardingAnswers {
  city: string
  transport: string
  food: string
  shopping: string
  energy: string
  name?: string
}

/**
 * AI-generated climate archetype returned by the scoring engine.
 *
 * Displayed on the onboarding reveal screen and the `/identity` page.
 *
 * @property name        - Archetype title (e.g. "Transit Star & Energy Auditor").
 * @property description - 1–2 sentence profile summary personalised to the user's city.
 * @property strength    - Positive reinforcement statement about the user's best category.
 * @property opportunity - Motivational statement about the user's highest-impact improvement area.
 */
export interface GeneratedIdentity {
  name: string
  description: string
  strength: string
  opportunity: string
}

/**
 * Future-state projection data used by the Climate Twin simulator on `/analysis`.
 *
 * All numbers are derived from a 35% baseline-reduction model applied to
 * the user's raw annual CO₂ emissions total.
 *
 * @property currentProjection  - Narrative sentence describing the current emissions trajectory.
 * @property improvedProjection - Narrative sentence describing projected savings after missions.
 * @property equivalents        - Real-world CO₂ savings equivalents for display.
 */
export interface ClimateTwinData {
  currentProjection: string
  improvedProjection: string
  equivalents: {
    /** Number of short-haul flights avoided (÷350 kg per flight). */
    flightsAvoided: number
    /** Months of average household grid power saved (÷450 kg per month). */
    householdPowerMonths: number
    /** Equivalent mature trees nourished for a year (÷22 kg per tree-year). */
    treesPlanted: number
  }
}

/**
 * A single carbon-saving mission surfaced by Clover for the user to complete.
 *
 * Missions are categorised by lifestyle area and ranked into three difficulty tiers.
 * AI Signature Missions (generated per user) differ from static daily eco-actions
 * in that they target the user's specific worst category for maximum impact.
 *
 * @property id           - Unique mission identifier (prefixed `sig_m_*` for AI missions).
 * @property title        - Short mission name shown in the missions hub card.
 * @property description  - 1–2 sentence action description with specific, actionable steps.
 * @property category     - Lifestyle category this mission targets.
 * @property points       - Carbon points awarded on completion (easy: 25, medium: 45, hard: 65).
 * @property co2SavingsKg - Estimated kg CO₂ saved per completion cycle.
 * @property difficulty   - Mission difficulty tier.
 * @property frequency    - How often this mission can be completed.
 * @property completed    - Whether the user has logged this mission in the current session.
 * @property reasoning    - Optional Clover explanation for why this mission was recommended.
 */
export interface AIMission {
  id: string
  title: string
  description: string
  category: "transport" | "energy" | "food" | "waste" | "shopping"
  points: number
  co2SavingsKg: number
  difficulty: "easy" | "medium" | "hard"
  frequency: "daily" | "weekly" | "one-time"
  completed?: boolean
  reasoning?: string
}

/**
 * Sends the user's onboarding answers to the `/api/profile` route and returns
 * a fully personalised climate profile generated by the scoring engine.
 *
 * The API route validates inputs with Zod before forwarding them to
 * `calculateProfile` in `scoring-engine.ts`. All computation is deterministic —
 * identical answers always produce identical results without an LLM call.
 *
 * @param answers - Validated onboarding answers from the Clover chat questionnaire.
 * @returns A promise resolving to the generated identity, narrative story,
 *          climate twin projection, and three signature missions.
 * @throws {Error} If the server responds with a non-OK HTTP status.
 */
export async function generateClimateProfile(answers: OnboardingAnswers): Promise<{
  identity: GeneratedIdentity
  story: string
  twin: ClimateTwinData
  missions: AIMission[]
}> {
  const response = await fetch("/api/profile", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: answers.name || "Eco Warrior",
      city: answers.city,
      transport: answers.transport,
      food: answers.food,
      shopping: answers.shopping,
      energy: answers.energy,
    }),
  })

  if (!response.ok) {
    throw new Error("Failed to generate climate profile from server")
  }

  const result = await response.json()
  return result.profile
}
