import { defineConfig } from "vitest/config"
import path from "path"

export default defineConfig({
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      "**/cypress/**",
      "**/.{idea,git,cache,output,temp}/**",
      "**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,playwright}.config.*",
      "tests/**",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: ["src/**/*"],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.test.tsx",
        "src/**/*.d.ts",
        "src/**/__snapshots__/**",
        "src/**/.gitkeep",
        "src/app/layout.tsx",
        "src/app/onboarding/onboarding-data.ts",
        "src/components/garden/Garden3D.tsx",
        "src/components/storytelling/Globe.tsx",
        "src/app/apple-touch-icon.png",
        "src/app/favicon.ico",
        "src/app/favicon.svg",
        "src/app/globals.css",
        "src/app/api/**",
        "src/app/garden/**",
        "src/components/shared/PageBackground.tsx",
        "src/components/shared/MainContentWrapper.tsx",
        "src/lib/ai-engine.ts",
        "src/data/**",
        "src/app/onboarding/page.tsx",
        "src/app/identity/page.tsx",
        "src/app/page.tsx",
        "src/components/shared/Navigation.tsx",
        "src/lib/category-utils.tsx",
        "src/app/analysis/ClimateTwinView.tsx",
        "src/app/analysis/page.tsx",
        "src/app/missions/page.tsx",
        "src/components/shared/Counter.tsx",
        "src/components/shared/LockedScreenPreview.tsx",
        "src/components/shared/ResetDemoButton.tsx",
        "src/store/AppContext.tsx",
        "node_modules/**",
        ".next/**",
        "next.config.ts",
        "postcss.config.mjs",
        "tailwind.config.ts",
      ],
    },
  },
})
